name:                amazon-scraper
version:             0.1.0.0
github:              "konn/amazon-scraper"
license:             BSD3
author:              "Hiromi ISHII"
maintainer:          "konn.jinro _at_ gmail.com"
copyright:           "2018 (c) Hiromi ISHII"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/konn/amazon-scraper#readme>

dependencies:
- base >= 4.7 && < 5
- http-client
- HandsomeSoup
- split
- text
- hxt
- wreq
- bytestring
- lens

ghc-options:
- -Wall

library:
  source-dirs: src

executables:
  amazon-scraper-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - amazon-scraper

tests:
  amazon-scraper-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - amazon-scraper
